### PR TITLE
After sign up structure

### PR DESCRIPTION
**Pull request by moayed-nabahin**

### CODE REVIEW

**Review by MohammedOmar123 — APPROVED** [review]

**Review by husamkamal — CHANGES_REQUESTED** [review]
Why use the img tag in the header and section after the input

**Review by husamkamal — CHANGES_REQUESTED** [review]
User tag the img in places it shouldn't be

**Comment by moayed-nabahin** [comment]
> User tag the img in places it shouldn't be

These images are for future usage as icons based on the design. This code is just a basic structure that holds all the necessary html tags needed in the page taking in mind that it could be changed while styling

**Comment by moayed-nabahin** [comment]
> Why use the img tag in the header and section after the input

they will be positioned using style above the input (search ,filter, voice icons )

**Pull request closed without merging**
